@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "org.example.petcareplus.service.impl.CategoryServiceImpl",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_1322970774 { 
   	label=example
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1394134074 { 
   	label=petcareplus
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   CartController1664927502[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)CartController</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   categoryService: CategoryService [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   productService: ProductService [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ buyNow(productId: Long, quantity: int, session: HttpSession, referer: String): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ clearCart(session: HttpSession): ResponseEntity&lt;?&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ getCartTotal(session: HttpSession): ResponseEntity&lt;Map&lt;String, Object&gt;&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ removeFromCart(productId: Long, session: HttpSession): ResponseEntity&lt;?&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ updateCart(payload: Map&lt;String, Object&gt;, session: HttpSession): ResponseEntity&lt;Map&lt;String, Object&gt;&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ viewCart(session: HttpSession, model: Model): String</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

CategoryServiceImpl101577557[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)CategoryServiceImpl</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   categoryRepository: CategoryRepository [1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

HomeController1664927502[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)HomeController</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   categoryService: CategoryService [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   productRepository: ProductRepository [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ Viewhome(model: Model): String</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

ListProductController1664927502[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ListProductController</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   categoryService: CategoryService [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   productRepository: ProductRepository [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ viewAllProducts(page: int, keyword: String, category: String, priceRange: Integer, searchkeyword: String, model: Model): String</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

ProductDetailController1664927502[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ProductDetailController</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   categoryService: CategoryService [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   productRepository: ProductRepository [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   productService: ProductService [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ showProductDetail(productId: Long, model: Model): String</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 
} 

'edges    
CartController1664927502 -> CategoryServiceImpl101577557[label="categoryService
[1]", arrowhead=none];
HomeController1664927502 -> CategoryServiceImpl101577557[label="categoryService
[1]", arrowhead=none];
ListProductController1664927502 -> CategoryServiceImpl101577557[label="categoryService
[1]", arrowhead=none];
ProductDetailController1664927502 -> CategoryServiceImpl101577557[label="categoryService
[1]", arrowhead=none];
    
}
@enduml